<script>
	import { trgmSearch, find_unique_trigrams } from 'js_trgm';
	console.log(find_unique_trigrams);

	const tutorials = {
		'Basics': 'basics',
		'Adding data': 'adding-data',
		'Dynamic attributes': 'dynamic-attributes',
		'Styling': 'styling',
		'Nested components': 'nested-components',
		'HTML tags': 'html-tags',
		'Making an app': 'making-an-app',
		'Assignments': 'reactive-assignments',
		'Declarations': 'reactive-declarations',
		'Statements': 'reactive-statements',
		'Updating arrays and objects': 'updating-arrays-and-objects',
		'Declaring props': 'declaring-props',
		'Default values': 'default-values',
		'Spread props': 'spread-props',
		'If blocks': 'if-blocks',
		'Else blocks': 'else-blocks',
		'Else-if blocks': 'else-if-blocks',
		'Each blocks': 'each-blocks',
		'Keyed each blocks': 'keyed-each-blocks',
		'Await blocks': 'await-blocks',
		'DOM events': 'dom-events',
		'Inline handlers': 'inline-handlers',
		'Event modifiers': 'event-modifiers',
		'Component events': 'component-events',
		'Event forwarding': 'event-forwarding',
		'DOM event forwarding': 'dom-event-forwarding',
		'Text inputs': 'text-inputs',
		'Numeric inputs': 'numeric-inputs',
		'Checkbox inputs': 'checkbox-inputs',
		'Group inputs': 'group-inputs',
		'Textarea inputs': 'textarea-inputs',
		'Select bindings': 'select-bindings',
		'Select multiple': 'multiple-select-bindings',
		'Contenteditable bindings': 'contenteditable-bindings',
		'Each block bindings': 'each-block-bindings',
		'Media elements': 'media-elements',
		'Dimensions': 'dimensions',
		'This': 'bind-this',
		'Component bindings': 'component-bindings',
		'Binding to component instances': 'component-this',
		'onMount': 'onmount',
		'onDestroy': 'ondestroy',
		'beforeUpdate and afterUpdate': 'update',
		'tick': 'tick',
		'Writable stores': 'writable-stores',
		'Auto-subscriptions': 'auto-subscriptions',
		'Readable stores': 'readable-stores',
		'Derived stores': 'derived-stores',
		'Custom stores': 'custom-stores',
		'Store bindings': 'store-bindings',
		'Tweened': 'tweened',
		'Spring': 'spring',
		'The transition directive': 'transition',
		'Adding parameters': 'adding-parameters-to-actions',
		'In and out': 'in-and-out',
		'Custom CSS transitions': 'custom-css-transitions',
		'Custom JS transitions': 'custom-js-transitions',
		'Transition events': 'transition-events',
		'Local transitions': 'local-transitions',
		'Deferred transitions': 'deferred-transitions',
		'Key blocks': 'key-blocks',
		'The animate directive': 'animate',
		'The use directive': 'actions',
		'The class directive': 'classes',
		'Shorthand class directive': 'class-shorthand',
		'Slots': 'slots',
		'Slot fallbacks': 'slot-fallbacks',
		'Named slots': 'named-slots',
		'Checking for slot content': 'optional-slots',
		'Slot props': 'slot-props',
		'setContext and getContext': 'context-api',
		'<svelte:self>': 'svelte-self',
		'<svelte:component>': 'svelte-component',
		'<svelte:window>': 'svelte-window',
		'<svelte:window> bindings': 'svelte-window-bindings',
		'<svelte:body>': 'svelte-body',
		'<svelte:head>': 'svelte-head',
		'<svelte:options>': 'svelte-options',
		'<svelte:fragment>': 'svelte-fragment',
		'Sharing code': 'sharing-code',
		'Exports': 'module-exports',
		'The @debug tag': 'debug',
		'Congratulations!': 'congratulations',
	};

	const search_in = Object.keys(tutorials);
	let value = '';

	$: results = JSON.stringify(trgmSearch(value, search_in, { limit: 1, threshold: 0.4 }), null, 4);
</script>

<input type="text" bind:value />
<pre><code>{results}</code></pre>
